create table businesspermits (
    ID int generated by default as identity(start with 1) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    VERSION integer,
    --
    status varchar(50),
    `amountPaid` integer,
    `expiryDate` date,
    `creationDate` date,
    `permitPayer` integer,
    description varchar(255),
    `businessID` integer,
    `activityCode` integer,
    `propertyRegisterID` integer,
    `numberOfEmployees` integer,
    `certificateNo` integer,
    `rcptNumber` integer
);
