create table revenuecollectors (
    ID int generated by default as identity(start with 1) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    VERSION integer,
    --
    name varchar(255),
    `idNumber` varchar(255),
    `deviceSN` varchar(255),
    `devicePIN` integer,
    `offlineCreditLimit` integer,
    `offlineRcptNumber` integer,
    `isBackOffice` boolean
);
