create table valuationrolls (
    ID int generated by default as identity(start with 1) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    VERSION integer,
    --
    `valuationCode` integer,
    name varchar(255) not null,
    `rollType` integer not null,
    `landUse` integer not null,
    `siteValue` varchar(255),
    `valuationMethod` integer,
    `ratingMethod` integer,
    `annualRate` varchar(255),
    `rentBasedOn` integer,
    exempt varchar(255),
    `rateableValue` varchar(255),
    `sizeInHa` integer,
    `subCounty` integer
);
