create table businesses (
    ID int generated by default as identity(start with 1) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    VERSION integer,
    --
    name varchar(255),
    description varchar(255),
    `regNo` varchar(255),
    email varchar(255),
    `phoneNumber` varchar(255),
    address varchar(255),
    status integer,
    town varchar(255),
    street varchar(255),
    `buildingName` varchar(255)
);
