create table revenuecollectiontransactions (
    ID int generated by default as identity(start with 1) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    VERSION integer,
    --
    `revenueStream` integer,
    `revenueCollector` integer,
    datetime timestamp,
    description varchar(255),
    `paymentMode` varchar(255),
    `paymentID` varchar(255),
    `revenueSection` integer,
    amount integer,
    `offlineID` varchar(255),
    `paymentModeID` integer,
    `reconStatus` integer,
    `reconFileID` integer
);
