create table revenuestreams (
    ID int generated by default as identity(start with 1) not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    VERSION integer,
    --
    category integer,
    `revenueCode` integer,
    `revenueName` varchar(255),
    price varchar(255),
    status integer,
    `defaultDebitAC` integer,
    `defaultCreditAC` integer,
    `revenuceCode` integer,
    department integer
);
